### ISSUE TITLE
Overview map with SSL

### ISSUE THREAD

**Issue by eleu** [camptocamp/demo_geomapfish#27]
The overview map still has a HTTP URL -> change it to HTTPS to avoid the insecure response error

![image](https://cloud.githubusercontent.com/assets/1632411/14181566/b2e02d12-f767-11e5-882e-83350704a979.png)

https://geomapfish-demo.camptocamp.net/2.0/theme/OSM

**Comment by sbrunner** [comment]
fixed with 9df9d96c505716c2d3a7f31103b1a861751ee815
