### ISSUE TITLE
Search for coordinates: ShowCenter true

### ISSUE THREAD

**Issue by eleu** [camptocamp/demo_geomapfish#33]
It would be nice to have the config

```
showCenter: true
```

in the FulltextSearch Plugin of the demo.

cf. http://docs.camptocamp.net/cgxp/1.6/lib/plugins/FullTextSearch.html#config-options

**Comment by yjacolin** [comment]
can be tested with http://yjacolin.gis.internal/yjacolin20/wsgi/theme/Transport

with 554320 209220

To comit  and make the PR
