### ISSUE TITLE
Use correct function for "open" link with "Open OSM" layer

### ISSUE THREAD

**Issue by llienher** [camptocamp/demo_geomapfish#58]
The demo should call this function here:
https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/controllers/abstract.js#L462

Instead it is actually using a cgxp function here:
https://github.com/camptocamp/demo_geomapfish/blob/master/mapserver/osm.map.mako#L1083

Consequence is that the  "open" link in WFS result is not working. It should open a window when clicking it.
![2017-07-12_12-11-22](https://user-images.githubusercontent.com/25748389/28117037-034ea32c-670c-11e7-8365-83abdf8ef225.png)
.

**Comment by sbrunner** [comment]
It's an ngeo issue ...
