### ISSUE TITLE
Incorrect printing of static images in the generated PDF

### ISSUE THREAD

**Issue by asaunier** [camptocamp/demo_geomapfish#62]
For instance when printing the following page:
https://geomapfish-demo.camptocamp.net/2.2?lang=fr&tree_group_layers_Transport=fuel&baselayer_ref=OSM%20map&map_crosshair=true&tree_groups=Transport

The crosshair (a static PNG file served using a "proj/" URL) is rejected (and replaced by a black square) because of an error similar to
> java.lang.IllegalArgumentException:
http://127.0.0.1/main/wsgi/proj/5d3163d34b894bb5b49ff07c48ff2116/images/crosshair.png is denied.

![capture du 2017-10-24 14-55-21](https://user-images.githubusercontent.com/1192331/31944154-6c355514-b8cb-11e7-923b-a1f25345867b.png)

This seems to be related to the print config at https://github.com/camptocamp/demo_geomapfish/blob/2.2/print/print-apps/demo/config.yaml.mako#L38-L76

For project SZ, @marionb has applied the following fix: https://github.com/camptocamp/schwyz_geoportal/pull/345/files
making sure the URLs of files in the "proj/" dir are not converted to localhost URLs.

Should we apply the fix to demo_geomapfish? If yes for what banch(es)? 2.2? master?

Should we apply the fix to the GMF scaffolds at https://github.com/camptocamp/c2cgeoportal/blob/master/geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/%2Bpackage%2B/config.yaml.mako#L38 (+ in some change log file?)? If yes for what branch(es)?

**Comment by sbrunner** [comment]
Should be fixed with https://github.com/camptocamp/demo_geomapfish/commit/74781b760afe9a958a1898310e05e058669e89fb

**Comment by asaunier** [comment]
@sbrunner Thanks! Feel free to close the issue if you think it is no longer relevent.
