### ISSUE TITLE
Metadata: cannot open metadata

### ISSUE THREAD

**Issue by svades** [camptocamp/demo_geomapfish#63]
On https://geomapfish-demo.camptocamp.net/2.2/theme/ObjectEditing?lang=de&tree_group_layers_Transport=fuel&baselayer_ref=OSM%20map&theme=ObjectEditing&tree_groups=ObjectEditing by clicking on the i-button of the layer "Punkt" a 404 error appears saying: The resource could not be found.
https://geomapfish-demo.camptocamp.net/2.2/wsgi/static-cgxp/htdocs/example.html

In the metadata window that we integrated on GMF 2.2.0 ngeo the layer name is not translated.
![metadata_layer_not_translated](https://user-images.githubusercontent.com/22655359/33547619-eda79704-d8e4-11e7-9bd1-b8290620171d.PNG)

**Comment by yjacolin** [comment]
The issue on metadaURL is corrected. Thanks.
For the second problem, it doesn't seem to be linked to demo GMF.
